"""Move policy owner, reviewer and public_viewable  to tenant level.

Revision ID: 6e764d47815e
Revises: eaa92316c761
Create Date: 2023-08-17 07:45:05.981562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e764d47815e'
down_revision = 'eaa92316c761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('public_viewable', sa.Boolean(), nullable=True))
    op.add_column('policies', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('policy_owner_id_fkey', 'policies', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key('policy_reviewer_id_fkey', 'policies', 'users', ['owner_id'], ['id'])
    op.drop_constraint('project_policies_owner_id_fkey', 'project_policies', type_='foreignkey')
    op.drop_constraint('project_policies_reviewer_id_fkey', 'project_policies', type_='foreignkey')
    op.drop_column('project_policies', 'reviewer_id')
    op.drop_column('project_policies', 'owner_id')
    op.drop_column('project_policies', 'public_viewable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_policies', sa.Column('public_viewable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project_policies', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project_policies', sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_policies_reviewer_id_fkey', 'project_policies', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key('project_policies_owner_id_fkey', 'project_policies', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'reviewer_id')
    op.drop_column('policies', 'public_viewable')
    op.drop_column('policies', 'owner_id')
    # ### end Alembic commands ###
