"""Insert default user and roles.

Revision ID: 7c45a144539d
Revises: d1ce0eef9cdc
Create Date: 2023-07-10 09:37:59.217852

"""
from alembic import op
import sqlalchemy as sa
from os import getenv
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '7c45a144539d'
down_revision = 'd1ce0eef9cdc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """INSERT into users(email, password, email_confirmed_at, built_in, super) VALUES ('{}', '{}', '{}', True, True)""".format(
            getenv('DEFAULT_EMAIL', 'admin@example.com'), generate_password_hash(getenv('DEFAULT_PASSWORD', 'admin')), sa.func.now()
        )
    )
    op.execute(
        """
            INSERT into roles (name, label) VALUES 
            ('admin', 'Admin'),
            ('editor', 'Editor'),
            ('viewer', 'Viewer'),
            ('user', 'User'),
            ('vendor', 'Vendor')
        """
    )


def downgrade():
    op.execute(f"DELETE from users where email = '{getenv('DEFAULT_EMAIL', 'admin@example.com')}'",)
    op.execute("DELETE FROM roles WHERE name IN ('admin', 'editor', 'viewer', 'user', 'vendor')"
    )
