"""Add evidence upload table.

Revision ID: 1c32718ccedd
Revises: 7c45a144539d
Create Date: 2023-07-12 09:08:25.230989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c32718ccedd'
down_revision = '7c45a144539d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('upload_link', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_link')
    )
    op.create_index(op.f('ix_evidence_uploads_evidence_id'), 'evidence_uploads', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_uploads_evidence_id'), table_name='evidence_uploads')
    op.drop_table('evidence_uploads')
    # ### end Alembic commands ###
