"""Add language column to policies table.

Revision ID: 784ff815f645
Revises: 6e764d47815e
Create Date: 2023-08-25 13:08:01.711866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784ff815f645'
down_revision = '6e764d47815e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('language', sa.String(length=3), server_default='eng', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'language')
    # ### end Alembic commands ###
