"""Introduce policy versioning.

Revision ID: eaa92316c761
Revises: 1c32718ccedd
Create Date: 2023-07-27 08:52:52.613593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa92316c761'
down_revision = '1c32718ccedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('policies', 'version')
    op.drop_column('policies', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('policies', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('policy_version')
    # ### end Alembic commands ###
